// <auto-generated />
using System;
using AccountingApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountingApp.Migrations
{
    [DbContext(typeof(AccountingContext))]
    [Migration("20210220135724_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountingApp.Models.DetaliiFactura", b =>
                {
                    b.Property<int>("IdDetaliiFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<string>("NumeProdus")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetaliiFactura", "IdLocatie");

                    b.ToTable("DetaliiFactura");
                });

            modelBuilder.Entity("AccountingApp.Models.Facturi", b =>
                {
                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("datetime");

                    b.Property<string>("NumarFactura")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeClient")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdFactura", "IdLocatie");

                    b.ToTable("Facturi");
                });
#pragma warning restore 612, 618
        }
    }
}
